ClassifierName: Slice Classifier Radio Acess Network # the name of this QOF
sbi: # Service-based interface information
  scheme: http # the protocol for sbi (http or https)
  registerIPv4: 172.16.100.10 # IP used to register to NRF
  bindingIPv4: 172.16.100.10  # IP used to bind the service
  port: 9092 # Port used to bind the service